### ISSUE TITLE
Ecrecover flag needs to be normalized

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui-axelar#1]
In https://github.com/MystenLabs/sui-axelar/blob/main/presets/index.js#L92 we directly pin `v=0` (last byte of signature) which is not technically correct and can be confusing. It works for the current example because it happened to be `v==0`.

Various partners use this repo as a template and they thought v should always be zero. We should add the logic to compute `v` according to https://tech.mystenlabs.com/cryptography-in-sui-cross-chain-signature-verification/

the algorithm is: 
```
// Compute v = 0 or 1.
   let v = vector::borrow_mut(&mut signature, 64);
   if (*v == 27) {
       *v = 0;
   } else if (*v == 28) {
       *v = 1;
   } else if (*v > 35) {
       *v = (*v - 1) % 2;
   };
```

**Comment by damirka** [comment]
Added a `normalize_signature` method with a link to the post in the Move code and started using `recid` parameter from the `secp256k1` library.

Thank you for pointing that out!
